# Types 

***


In [4]:
type (145 / 67)


float

In [3]:
type (45-67)

int

In [6]:
type (8/2)

float

In [7]:
type (8//2)

int

# numpy

***

In [5]:
import numpy as np


In [8]:
ls = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [10]:
print (ls)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
ls.dtype

dtype('int32')

In [18]:
# Roll a dice
rolls = np.random.randint(1,7,10)

In [20]:
# Average roll.
np.mean(rolls)

4.0